apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: sdk-sbx.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Awesome demo operator
  displayName: SDK Sandbox Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - awesome
  - demo
  - eriknelson
  links:
  - name: Sdk Sbx
    url: https://sdk-sbx.domain
  maintainers:
  - email: erik@nsk.io
    name: eriknelson
  maturity: alpha
  provider:
    name: operators.nsk.io
  version: 0.0.0
